### ISSUE TITLE
help help ！

### ISSUE THREAD

**Issue by lichunlei4** [SCCapstone/RobotCA#63]
How to add a topic in your project！

**Comment by mtbii** [comment]
If you want a make a publisher, you can look at [RobotController:432](https://github.com/SCCapstone/RobotCA/blob/b9dd2b913755b6d96d47ab1ad88041ff88502efd/src/android_foo/control_app/src/main/java/com/robotca/ControlApp/Core/RobotController.java#L423) for reference.

**Comment by lichunlei4** [comment]
I mean to add one user-defined topic .The  parameter is  java.lang.String.
Do you undestand ?(I am  from China !My English is so poor！)

**Comment by mtbii** [comment]
Do you want to allow a user to add a topic in the app? This feature was not
part of the app as far as I know.

Or do you mean you want to add a new topic to the app and have the user
pick the name? This would be similar to how we handled the topics
 (joystick, navsat, etc.) that are already in the app.

Can you clarify? I'm not sure what you mean. Your English isn't bad. I just
need more information and context.

**Comment by lichunlei4** [comment]
I mean is to add a new topic to the app and have the user
pick the name. I tried but it didn't  work !Can you give me an example?

**Comment by lichunlei4** [comment]
I mean is to add a new topic to the app and have the user
pick the name. I tried but it didn't work !Can you give me an example?
(the topic has a parameter type is std_msgs::String::ConstPtr)!

**Comment by mtbii** [comment]
Oh ok. There's a few things you need to do for that.

1. Add the topic to [RobotInfo](https://github.com/mtbii/RobotCA/blob/ffb625e6faab9528ee2020e235a87601a297641b/src/android_foo/control_app/src/main/java/com/robotca/ControlApp/Core/RobotInfo.java). This is the main class for a robot's configuration. Other classes use the constants and data in there to subscribe, publish, and save preferences for each robot.
2. Add the topic to the [AddEditRobotDialog](https://github.com/mtbii/RobotCA/blob/ffb625e6faab9528ee2020e235a87601a297641b/src/android_foo/control_app/src/main/java/com/robotca/ControlApp/Dialogs/AddEditRobotDialogFragment.java). This allows the user to add/edit topics for a robot before they connect.
3. Add the topic to the [Preferences](https://github.com/mtbii/RobotCA/blob/ffb625e6faab9528ee2020e235a87601a297641b/src/android_foo/control_app/src/main/res/xml/prefs.xml) file. This file is used to make the settings view that allows the user to edit the topics after they have connected to a robot.
4. Update [RobotStorage](https://github.com/mtbii/RobotCA/blob/ffb625e6faab9528ee2020e235a87601a297641b/src/android_foo/control_app/src/main/java/com/robotca/ControlApp/Core/RobotStorage.java) with the new topic so that it can load/save the topic from/to SharedPreferences.

It would probably be easiest to copy the existing pattern for topics that are already in the app like navsat, pose, or joystick.

**Comment by lichunlei4** [comment]
this project have a bug ! some time cannot move to forward~！Do you know way~！

**Comment by lichunlei4** [comment]
how to change the ros‘s speed？？

**Comment by mtbii** [comment]
I'm not sure why moving forward wouldn't work. This code is not the best quality since it was done over a few months with minimal testing. It's not being maintained anymore so there won't be any bug fixes.

What do you mean by the ros's speed? You mean the robot's speed? That's a setting you have to change. I don't know anything about your configuration.

**Comment by lichunlei4** [comment]
OH~!Thanks mtbii~!Mtbii is your real name?? Do you have a better Code??

**Comment by mtbii** [comment]
Not my real name. If click on my name here you can see all my info in my GitHub profile including my real name (which is Michael).

I don't have better code unfortunately. This was a project I worked on with a few other people during my last year in college in a senior-level capstone design course. It was for a robotics research group at my university and no one has touched the code in a year or so because we all graduated and got jobs that keep us busy. That's why I put "No longer maintained, please fork or PR" in the README. It has only been tested on a few robots in the lab. I made the code public so others could (hopefully) learn and do better and more interesting things with the code.

**Comment by lichunlei4** [comment]
Well, your programming skills are very powerful!

**Comment by lichunlei4** [comment]
你现在做什么工作呢？方便说吗？

**Comment by mtbii** [comment]
I'm a software engineer at Google now working on [Android Things](https://developer.android.com/things/index.html). Very fun, but very time consuming and difficult.

**Comment by mtbii** [comment]
I used to work on Chrome. I created the chrome://bluetooth-internals page (which most people have never seen. Haha.).

**Comment by lichunlei4** [comment]
I'm also a Android developer, but I'm just a newbie! You are too fierce. I must learn from you!

**Comment by mtbii** [comment]
I haven't been doing Android that long, but I know enough to get some basic stuff done.

**Comment by lichunlei4** [comment]
That enough~!What subject did you study at university？ What kind of development are you good at?

**Comment by mtbii** [comment]
I studied computer engineer. It's a mix of computer science and electrical engineering (mostly computer science though). Most of my experience is in web development: HTML, JS, CSS, React, and Angular. I just started doing Android platform stuff: interacting with hardware drivers, adding new APIs to Android itself, and writing apps to test the new APIs.

**Comment by lichunlei4** [comment]
Why the project can't load the map?

**Comment by mtbii** [comment]
I just noticed this is the out of date repo so you might want to move to the cloned one:
https://github.com/mtbii/RobotCA

Or better yet, ros-autom has an **updated version** that was forked from my cloned repo.
https://github.com/ros-autom/RobotCA
